### PR TITLE
adds coverage for all stackexchange network sites

### PR DESCRIPTION
**Pull request by drammock**
adds patterns to match all sites in the stackexchange network.  Tested using `about:debugging` mode.

### CODE REVIEW

**Comment by drammock** [comment]
@DanArthurGallagher I didn't increment the version because I wasn't sure whether you'd view this kind of change as a `1.3.6.1` or `1.3.7.0` or `1.4.0.0` (presumably not big enough for a `2.0.0.0`)

**Comment by danieleloscozzese** [comment]
Thank you very much @drammock!
I’ll pull this in as 1.4.

**Comment by danieleloscozzese** [comment]
## To-Do
* [x] Update the version to `1.4.0.0`
* [x] Update the localisations to reflect the inclusion of the network sites

**Review by danieleloscozzese — APPROVED** [review]
This is really handy work, and thanks very much for doing it!

**Pull request merged**
